# Generated by Django 3.2.8 on 2022-06-27 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login_id', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('hint', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_date', models.DateField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField()),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_total', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_doc', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('alias', models.CharField(max_length=60, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('student_id', models.CharField(blank=True, max_length=200, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_enrollment', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('avater', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, default='DEFAULT VALUE', max_length=200, null=True)),
                ('tutor', models.CharField(blank=True, max_length=200)),
                ('course_code', models.IntegerField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('time', models.TimeField(auto_now=True)),
                ('phone_no', models.IntegerField()),
                ('assistance_tutor', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField()),
                ('student_group', models.CharField(blank=True, max_length=200, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_class_code', models.IntegerField(blank=True, default=0, null=True)),
                ('student_total', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('student_id', models.CharField(blank=True, max_length=200, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_enrollment', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_id', models.IntegerField()),
                ('Subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Subject_Teacher', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_id', models.IntegerField()),
                ('Teacher_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Teacher_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('Teacher_total', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('subject_assignment_marks', models.FloatField(default=0)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar.student')),
                ('subject_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lunar.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('Attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar.attendance')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='Student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.subject'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('appointment_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar.attendance')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.student')),
            ],
        ),
    ]
