# Generated by Django 3.2.8 on 2021-12-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0002_rename_course_class_course_course_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_date', models.DateField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_id', models.IntegerField()),
                ('Subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Subject_Teacher', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_id', models.IntegerField()),
                ('Teacher_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Teacher_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('Teacher_total', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('subject_assignment_marks', models.FloatField(default=0)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar.student')),
                ('subject_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lunar.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('Attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar.attendance')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='Subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.subject'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('appointment_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunar.attendance')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lunar.student')),
            ],
        ),
    ]
