# Generated by Django 3.2.8 on 2022-06-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0004_teacher_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.TimeField(null=True),
        ),
    ]
