# Generated by Django 3.2.8 on 2022-01-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0005_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('course_code', models.IntegerField(blank=True, default=0, null=True)),
                ('dox_purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('Due', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
