# Generated by Django 3.2.8 on 2022-01-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0006_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
