# Generated by Django 3.2.8 on 2022-01-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0007_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Session',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
