# Generated by Django 3.2.8 on 2022-01-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0008_auto_20220123_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='phone_no',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
