# Generated by Django 3.2.8 on 2022-01-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0010_auto_20220123_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='course',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='dox_purpose',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='course_code',
        ),
    ]
