# Generated by Django 3.2.8 on 2022-01-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0011_auto_20220123_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Due',
            new_name='due',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='dox_purpose',
        ),
    ]
