# Generated by Django 3.2.8 on 2022-02-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0013_assignments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
