# Generated by Django 3.2.8 on 2022-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0018_auto_20220301_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
