# Generated by Django 3.2.8 on 2022-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0019_documents_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentList',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('documents', models.ManyToManyField(related_name='documents', to='lunar.Documents')),
            ],
        ),
    ]
