# Generated by Django 3.2.8 on 2022-03-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0020_documentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='name_doc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentList',
        ),
    ]
