# Generated by Django 3.2.8 on 2022-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0021_auto_20220312_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='assistance_tutor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
