# Generated by Django 3.2.8 on 2022-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0022_auto_20220505_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
