# Generated by Django 3.2.8 on 2022-05-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunar', '0023_assignments_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='course_name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=200, null=True),
        ),
    ]
